<a href="https://colab.research.google.com/github/Shiva007-RAndom/Task-1/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##Introduction to tensors

###Creating tensors

In [2]:
#scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#matrix
matrix=torch.tensor([[1,2],
                    [5,6]])
matrix

tensor([[1, 2],
        [5, 6]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#tensor
tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
tensor[0][2][1]

tensor(8)

###Random Tensors

In [15]:
#creating a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8714, 0.1033, 0.1660, 0.8212],
        [0.8155, 0.0760, 0.3851, 0.4381],
        [0.4323, 0.1415, 0.0823, 0.5453]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor=torch.rand(1,3,5)
random_tensor

tensor([[[0.0532, 0.5281, 0.7011, 0.3340, 0.8278],
         [0.3539, 0.4758, 0.4354, 0.8107, 0.5899],
         [0.7839, 0.2047, 0.4302, 0.0295, 0.9968]]])

In [18]:
random_tensor.ndim,random_tensor.shape

(3, torch.Size([1, 3, 5]))

In [19]:
zero=torch.zeros(1,2,3)
zero

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [20]:
ones=torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
#creating a tensor with range
range_tensor=torch.arange(start=0,end=1000,step=15)
range_tensor

tensor([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180, 195,
        210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405,
        420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615,
        630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825,
        840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990])

In [23]:
#to create tensors with similar shape to another tensor
zeros_like=torch.zeros_like(input=range_tensor)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [24]:
float_16_tensor=torch.tensor([[9,8,7],
                              [6,7,8]],
                             dtype=torch.float16)
float_16_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float16)

In [25]:
torch.tensor([1,2,3],
             dtype=None, #to edit the datatype of the tensor
             device=None, #what device the tensor is on
             requires_grad=False) #whether or not to track the gradients

tensor([1, 2, 3])

In [26]:
float_64_tensor=float_16_tensor.type(torch.float64)
float_64_tensor

tensor([[9., 8., 7.],
        [6., 7., 8.]], dtype=torch.float64)

In [27]:
float_16_tensor*float_64_tensor

tensor([[81., 64., 49.],
        [36., 49., 64.]], dtype=torch.float64)

In [28]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
float_16_tensor*int_32_tensor

tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

###Getting attributes from tensor

1. Getting datatype- use tensor.dtype
2. Getting shape   - use tensor.shape
3. Getting device  - use tensor.device

In [30]:
tensor_random=torch.rand(3,4,5)
tensor_random

tensor([[[0.2897, 0.7922, 0.3203, 0.6519, 0.1016],
         [0.3552, 0.8777, 0.8028, 0.9625, 0.9774],
         [0.7261, 0.9944, 0.2652, 0.0978, 0.6294],
         [0.0730, 0.5775, 0.8710, 0.1962, 0.9445]],

        [[0.8754, 0.3111, 0.6939, 0.4581, 0.3957],
         [0.9428, 0.5059, 0.4212, 0.8940, 0.4388],
         [0.2418, 0.8101, 0.1487, 0.3237, 0.3027],
         [0.6210, 0.3296, 0.9354, 0.3256, 0.8966]],

        [[0.2285, 0.0176, 0.8536, 0.7294, 0.6726],
         [0.9433, 0.4353, 0.7598, 0.1301, 0.8676],
         [0.1652, 0.4943, 0.3646, 0.7752, 0.2790],
         [0.2165, 0.1923, 0.8056, 0.9025, 0.2339]]])

In [31]:
tensor_random.shape,tensor_random.dtype,tensor_random.device

(torch.Size([3, 4, 5]), torch.float32, device(type='cpu'))

In [32]:
int_32_tensor.shape,int_32_tensor.dtype,int_32_tensor.device

(torch.Size([3]), torch.int32, device(type='cpu'))

###Tensor Operations

1. Addition
2. Subtraction
3. Multiplication
4. division
5. Matrix Multiplication

In [33]:
#addition
tensor_random+10

tensor([[[10.2897, 10.7922, 10.3203, 10.6519, 10.1016],
         [10.3552, 10.8777, 10.8028, 10.9625, 10.9774],
         [10.7261, 10.9944, 10.2652, 10.0978, 10.6294],
         [10.0730, 10.5775, 10.8710, 10.1962, 10.9445]],

        [[10.8754, 10.3111, 10.6939, 10.4581, 10.3957],
         [10.9428, 10.5059, 10.4212, 10.8940, 10.4388],
         [10.2418, 10.8101, 10.1487, 10.3237, 10.3027],
         [10.6210, 10.3296, 10.9354, 10.3256, 10.8966]],

        [[10.2285, 10.0176, 10.8536, 10.7294, 10.6726],
         [10.9433, 10.4353, 10.7598, 10.1301, 10.8676],
         [10.1652, 10.4943, 10.3646, 10.7752, 10.2790],
         [10.2165, 10.1923, 10.8056, 10.9025, 10.2339]]])

In [34]:
#multiplication
tensor_random*21

tensor([[[ 6.0839, 16.6357,  6.7266, 13.6899,  2.1346],
         [ 7.4587, 18.4326, 16.8579, 20.2117, 20.5256],
         [15.2490, 20.8820,  5.5684,  2.0540, 13.2167],
         [ 1.5323, 12.1283, 18.2907,  4.1209, 19.8351]],

        [[18.3827,  6.5327, 14.5723,  9.6197,  8.3105],
         [19.7993, 10.6232,  8.8454, 18.7749,  9.2156],
         [ 5.0779, 17.0111,  3.1219,  6.7976,  6.3565],
         [13.0413,  6.9222, 19.6425,  6.8368, 18.8296]],

        [[ 4.7987,  0.3687, 17.9254, 15.3180, 14.1255],
         [19.8099,  9.1415, 15.9549,  2.7318, 18.2202],
         [ 3.4689, 10.3807,  7.6560, 16.2783,  5.8600],
         [ 4.5468,  4.0375, 16.9175, 18.9531,  4.9128]]])

In [35]:
#subtraction
tensor_random-9

tensor([[[-8.7103, -8.2078, -8.6797, -8.3481, -8.8984],
         [-8.6448, -8.1223, -8.1972, -8.0375, -8.0226],
         [-8.2739, -8.0056, -8.7348, -8.9022, -8.3706],
         [-8.9270, -8.4225, -8.1290, -8.8038, -8.0555]],

        [[-8.1246, -8.6889, -8.3061, -8.5419, -8.6043],
         [-8.0572, -8.4941, -8.5788, -8.1060, -8.5612],
         [-8.7582, -8.1899, -8.8513, -8.6763, -8.6973],
         [-8.3790, -8.6704, -8.0646, -8.6744, -8.1034]],

        [[-8.7715, -8.9824, -8.1464, -8.2706, -8.3274],
         [-8.0567, -8.5647, -8.2402, -8.8699, -8.1324],
         [-8.8348, -8.5057, -8.6354, -8.2248, -8.7210],
         [-8.7835, -8.8077, -8.1944, -8.0975, -8.7661]]])

In [36]:
#functions
tensor=torch.mul(tensor_random,10)
print(f"Multiplying 10 : {tensor}")
tensor=torch.add(tensor_random,10)
print(f"Adding 10 : {tensor}")

Multiplying 10 : tensor([[[2.8971, 7.9217, 3.2031, 6.5190, 1.0165],
         [3.5518, 8.7774, 8.0276, 9.6246, 9.7741],
         [7.2614, 9.9438, 2.6516, 0.9781, 6.2937],
         [0.7297, 5.7754, 8.7098, 1.9623, 9.4453]],

        [[8.7536, 3.1108, 6.9392, 4.5808, 3.9574],
         [9.4283, 5.0587, 4.2121, 8.9404, 4.3884],
         [2.4180, 8.1005, 1.4866, 3.2370, 3.0269],
         [6.2102, 3.2963, 9.3536, 3.2556, 8.9665]],

        [[2.2851, 0.1756, 8.5359, 7.2943, 6.7264],
         [9.4333, 4.3531, 7.5976, 1.3009, 8.6763],
         [1.6518, 4.9432, 3.6457, 7.7516, 2.7905],
         [2.1652, 1.9226, 8.0560, 9.0253, 2.3395]]])
Adding 10 : tensor([[[10.2897, 10.7922, 10.3203, 10.6519, 10.1016],
         [10.3552, 10.8777, 10.8028, 10.9625, 10.9774],
         [10.7261, 10.9944, 10.2652, 10.0978, 10.6294],
         [10.0730, 10.5775, 10.8710, 10.1962, 10.9445]],

        [[10.8754, 10.3111, 10.6939, 10.4581, 10.3957],
         [10.9428, 10.5059, 10.4212, 10.8940, 10.4388],
         [10.24

####Matrix Multiplication

1. Element wise multiplication
2. Multiplying with another matrix i.e dot product

In [37]:
#Element wise multiplication
element_mul=int_32_tensor*float_16_tensor
element_mul

tensor([[27., 48., 63.],
        [18., 42., 72.]], dtype=torch.float16)

In [38]:
#matrix multiplicationt
tensor_1=torch.rand(4,5)
tensor_2=torch.rand(5,4)

mat_mul=torch.matmul(tensor_1,tensor_2)
mat_mul_short=torch.mm(tensor_1,tensor_2)#alias of matmul
mat_mul,mat_mul_short

(tensor([[1.2015, 0.6643, 1.0929, 1.2468],
         [1.4613, 1.2569, 1.1581, 1.6714],
         [0.9534, 1.0282, 0.6038, 1.1488],
         [1.8718, 1.3976, 1.4434, 1.3432]]),
 tensor([[1.2015, 0.6643, 1.0929, 1.2468],
         [1.4613, 1.2569, 1.1581, 1.6714],
         [0.9534, 1.0282, 0.6038, 1.1488],
         [1.8718, 1.3976, 1.4434, 1.3432]]))

In [39]:
#the most common error in matrix multiplication : shape error
tensor_mul_1=torch.rand(3,4)
tensor_mul_2=torch.rand(2,3)

mat_mul_tensor=torch.matmul(tensor_mul_1,tensor_mul_2) #the inner dimensions must match
mat_mul_tensor

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 2x3)

In [40]:
#using transpose
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
tensor_A.T,tensor_B.T

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [41]:
tensor_C=torch.mm(tensor_A,tensor_B.T)
tensor_C

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Tensor Aggregation
1. Mean
2. Max
3. Min
4. Sum

In [42]:
x=torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [43]:
#min
torch.min(x)

tensor(0)

In [44]:
#max
torch.max(x)

tensor(95)

In [45]:
#mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

torch.mean doesnt work with int types.

In [46]:
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [47]:
#sum
torch.sum(x)

tensor(950)

###Positional min and max

In [48]:
#positional minimum
x.argmin()

tensor(0)

In [49]:
#positional maximum
x.argmax()

tensor(19)

In [50]:
x[0],x[19]

(tensor(0), tensor(95))

###Reshaping,stacking,squeezing and unsqueezing tensors

* Reshaping- reshaping the input tensor to a different tensor
* View     - return a view of an input tensor of certain shape but keep memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze  - remove dimensions from tensor
* Unsqueeze- add dimension to a tensor
* Permute  - return a view of the input with the dimensions permuted in a certain way

In [51]:
x=torch.arange(1.,50.,5)
x

tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.])

In [52]:
x.shape

torch.Size([10])

In [53]:
#reshaping
x_reshaped=x.reshape(5,2) #reshape has to be compatible with original shape
x_reshaped

tensor([[ 1.,  6.],
        [11., 16.],
        [21., 26.],
        [31., 36.],
        [41., 46.]])

In [54]:
#change the view
z=x.view(10,1)
z,z.shape

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [36.],
         [41.],
         [46.]]),
 torch.Size([10, 1]))

In [55]:
#changing z changes x because a view share the original tensor's memory
z[7,:]=52
z,x

(tensor([[ 1.],
         [ 6.],
         [11.],
         [16.],
         [21.],
         [26.],
         [31.],
         [52.],
         [41.],
         [46.]]),
 tensor([ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]))

In [56]:
#stacking
x_stacked=torch.stack([x,x],dim=0)
x_stacked

tensor([[ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.],
        [ 1.,  6., 11., 16., 21., 26., 31., 52., 41., 46.]])

In [57]:
x_stacked=torch.stack([x,x],dim=1)
x_stacked

tensor([[ 1.,  1.],
        [ 6.,  6.],
        [11., 11.],
        [16., 16.],
        [21., 21.],
        [26., 26.],
        [31., 31.],
        [52., 52.],
        [41., 41.],
        [46., 46.]])

In [58]:
#squeezing
x=torch.arange(0.,10.)
x_reshaped=x.reshape(1,10)

x_squeezed=torch.squeeze(x_reshaped,dim=0)
x_squeezed

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
x_reshaped.shape,x_squeezed.shape

(torch.Size([1, 10]), torch.Size([10]))

In [60]:
#unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
x_unsqueezed.shape

torch.Size([10, 1])

In [61]:
#permuting-returns a view with dimensions rearranged
x=torch.ones(size=(4,2,7))
x


tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])

In [62]:
x_permuted=x.permute(2,0,1) #shifts axis 0->2, 1->0, 2->1


In [63]:
x_permuted.shape,x.shape

(torch.Size([7, 4, 2]), torch.Size([4, 2, 7]))

###Indexing in PyTorch

In [64]:
x=torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [65]:
#indexing on the tensor
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [66]:
x[0][0],x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [67]:
x[0,1,1]

tensor(5.)

In [68]:
x[0,2,1]

tensor(8.)

In [69]:
#using : to select all values of a particular dimension
x[:,2]

tensor([[7., 8., 9.]])

In [70]:
x[:,2,:]

tensor([[7., 8., 9.]])

In [71]:
x[0,:,:]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

##PyTorch and NumPy

PyTorch has functionality to interact with NumPy

* Data in NumPy to PyTorch tensor `torch.from_numpy(ndarray)`
* Data in PyTorch tensor to NumPy `torch.Tensor.numpy(ndaray)`

In [72]:
import torch
import numpy as np

array=np.arange(1.,8.)
tensor=torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

When converting from numpy to pytorch it reflects the datatype of numpy which is float64 whereas as the default datatype of torch is float32

In [73]:
tensor=torch.ones(size=(3,3))
numpy_tensor=tensor.numpy()

In [74]:
tensor,numpy_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

##Reproducability
To reduce randomness we use **random seed**.

In [75]:
#creating 2 random tensors
random_tensor_A=torch.rand(4,5)
random_tensor_B=torch.rand(4,5)
random_tensor_A,random_tensor_B

(tensor([[0.3163, 0.4855, 0.9846, 0.9366, 0.2685],
         [0.7170, 0.4934, 0.2872, 0.5517, 0.6529],
         [0.8865, 0.8815, 0.2886, 0.4272, 0.1615],
         [0.8565, 0.3950, 0.2406, 0.3173, 0.1030]]),
 tensor([[0.0546, 0.0564, 0.8432, 0.3059, 0.3636],
         [0.3554, 0.2397, 0.7679, 0.1627, 0.0510],
         [0.9437, 0.1919, 0.5246, 0.7009, 0.6254],
         [0.1456, 0.2057, 0.3596, 0.0326, 0.5544]]))

In [76]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [77]:
#setting a random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(4,5)

torch.manual_seed(42)
random_tensor_D=torch.rand(4,5)

print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


Use `torch.manal_seed()` every time you use a torch function because it works for only one instance of torch

##Running tensors and PyTorch objects on the GPU's


###Getting a GPU

1. Use the google colab gpu's
2. Use your own GPU
3. Use cloud computing- GCP,AWS and AZURE

For 2,3 PyTorch+CUDA will need some setting up

In [78]:
##Checking for GPU
torch.cuda.is_available()

True

In [79]:
#Setup device agnostic code
device='cuda' if torch.cuda.is_available() else 'cpu' #if gpu is available set device to cuda or else make it cpu
device

'cuda'

In [80]:
torch.cuda.device_count() #counting the number of gpu's

1

###Putting Tensors to GPU's

In [81]:
#creating a tensor
tensor=torch.rand([4,5],device='cpu')
print(tensor,tensor.device)




tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]]) cpu


In [82]:
#move tensor to gpu
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]], device='cuda:0')

In [83]:
#if tensor is on gpu we cant convert it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [84]:
#to fix the above thing
tensor_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([[0.26963168, 0.44136357, 0.29692084, 0.8316855 , 0.10531491],
       [0.26949483, 0.35881263, 0.19936377, 0.54719156, 0.00616044],
       [0.95155454, 0.07526588, 0.8860137 , 0.5832096 , 0.33764774],
       [0.808975  , 0.5779254 , 0.9039817 , 0.55465984, 0.3423134 ]],
      dtype=float32)